services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - ./assets/db:/docker-entrypoint-initdb.d
  cache:
    extends:
      file: docker-compose.yml
      service: cache
  api:
    extends:
      file: docker-compose.yml
      service: api
    env_file:
      - api.env
    ports:
      - 8055:8055
    volumes:
      - ./packages/patchbay/bundle:/directus/extensions/patchbay
      - ./assets/api/uploads:/directus/uploads
volumes:
  extensions:
  snapshots:
