services:
  db:
    image: postgis/postgis:13-master
    container_name: patchbay_db
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ${PATCHBAY_DATA_DIR:-~/directus}/database:/var/lib/postgresql/data
      - ${PATCHBAY_SEED_VOLUME:-seed}:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${PATCHBAY_POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${PATCHBAY_POSTGRES_PASSWORD:-patchbay}"
      POSTGRES_DB: "${PATCHBAY_POSTGRES_DB:-patchbay}"
  cache:
    image: redis:6
    container_name: patchbay_cache

  api:
    image: directus/directus:11.7.2
    container_name: patchbay_api
    volumes:
      - ${PATCHBAY_EXTENSION_VOLUME:-extensions}:/directus/extensions
      - ${PATCHBAY_UPLOADS_VOLUME:-uploads}:/directus/uploads
    environment:
      SECRET: "${PATCHBAY_SECRET:-patchbay_super_secret}"

      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "${PATCHBAY_POSTGRES_DB:-patchbay}"
      DB_USER: "${PATCHBAY_POSTGRES_USER:-admin}"
      DB_PASSWORD: "${PATCHBAY_POSTGRES_PASSWORD:-patchbay}"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "${PATCHBAY_ADMIN_EMAIL:-admin@patchbay.io}"
      ADMIN_PASSWORD: "${PATCHBAY_ADMIN_PASSWORD:-patchbay}"

      PUBLIC_URL: "http://localhost:3000/patchbay"
      ROOT_REDIRECT: "/patchbay"
  app:
    container_name: patchbay_app
    image: artificialhoney/patchbay:latest
    ports:
      - 3000:3000
    volumes:
      - ${PATCHBAY_EXTENSIONS_VOLUME:-extensions}:/app/api/extensions
      - ${PATCHBAY_UPLOADS_VOLUME:-uploads}:/app/api/uploads
      - ${PATCHBAY_SEED_VOLUME:-seed}:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  uploads:
  extensions:
  seed:
