services:
  db:
    extends:
      file: docker-compose.yml
      service: db
  cache:
    extends:
      file: docker-compose.yml
      service: cache
  api:
    extends:
      file: docker-compose.yml
      service: api
    env_file:
      - api.env
