services:
  database:
    image: postgis/postgis:13-master
    container_name: patchbay_postgis
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ${PATCHBAY_DATA_DIR:-~/directus}/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PATCHBAY_POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${PATCHBAY_POSTGRES_PASSWORD:-patchbay}"
      POSTGRES_DB: "${PATCHBAY_POSTGRES_DB:-patchbay}"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--host=localhost",
          "--username=${PATCHBAY_POSTGRES_USER:-admin}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    container_name: patchbay_redis
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.7.2
    container_name: patchbay_directus
    volumes:
      - ${PATCHBAY_DATA_DIR:-~/directus}/uploads:/directus/uploads
      - ${PATCHBAY_DATA_DIR:-~/directus}/templates:/directus/templates
      - extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: "${PATCHBAY_SECRET:-patchbay_super_secret}"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "${PATCHBAY_POSTGRES_DB:-patchbay}"
      DB_USER: "${PATCHBAY_POSTGRES_USER:-admin}"
      DB_PASSWORD: "${PATCHBAY_POSTGRES_PASSWORD:-patchbay}"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "${PATCHBAY_ADMIN_EMAIL:-admin@patchbay.io}"
      ADMIN_PASSWORD: "${PATCHBAY_ADMIN_PASSWORD:-patchbay}"

      PUBLIC_URL: "http://localhost:8080/api"
  patchbay:
    container_name: patchbay_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - extensions:/directus/extensions/patchbay
    depends_on:
      - directus
volumes:
  extensions:
