sharedWorkspaceLockfile: true

packages:
  - packages/cables/*
  - packages/patchbay/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - esbuild
  - sharp
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
