import chroma from "chroma-js";
import loadjs from "loadjs";
import introJs from "intro.js";
import { iziToast } from "./izitoast.js";
import { marked } from "marked";
import moment from "moment-mini";
import pako from "pako";
import socketClusterClient from "socketcluster-client";
import ErrorStackParser from "error-stack-parser";
import "tinysort";
import Sortable from "sortablejs";
import platform from "platform";
import Raphael from "raphael";

import QRCode from "./qrcode.js";
import Handlebars from "handlebars";
import hljs from "highlight.js";
import ColorRick from "./colorrick.js";
import MathParser from "./mathparser.js";
import UndoManager from "undo-manager";

window.chroma = chroma;
window.ColorRick = ColorRick;
window.Handlebars = Handlebars;
window.hljs = hljs;
window.introJs = introJs;
window.iziToast = iziToast;
window.loadjs = loadjs;
window.marked = marked;
window.MathParser = MathParser;
window.moment = moment;
window.pako = pako;
window.QRCode = QRCode;
window.socketClusterClient = socketClusterClient;
window.ErrorStackParser = ErrorStackParser;
window.UndoManager = UndoManager;
window.Sortable = Sortable;
window.platformLib = platform;
window.Raphael = Raphael;
