name: Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  docker:
    environment: docker.io
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: artificialhoney/patchbay
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, Tag, and push the Docker image - latest
        if: ${{ github.ref_name == 'main' }}
        env:
          IMAGE_TAG: latest
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Build, Tag, and push the Docker image
        if: ${{ github.ref_name != 'main' }}
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
